// address type
export const GET_IDENTITY_ADDRESS = 'GET_IDENTITY_ADDRESS'
export const GET_HYDRO_ADDRESS = 'GET_HYDRO_ADDRESS'
export const ADDRESS_ERROR = 'ADDRESS_ERROR'
export const IS_HYDRO_ID_AVAILABLE = 'IS_HYDRO_ID_AVAILABLE'

//error
export const CLEAR_ERRORS = 'CLEAR_ERRORS'